### ISSUE TITLE
How to backup the whote site automatcially? 

### ISSUE THREAD

**Issue by gulprun** [webrecorder/archiveweb.page-site#8]
The archive tool (desktop) is amazingly simple, but I can't find a place to archive a web site as a whole starting from homepage, e.g. https://inmediahk.net. I guess auto-pilot is only for page scrolling if I'm not wrong. 

Does it only support page by page archiving?

**Comment by DaleLore** [comment]
You're exactly right. The auto-pilot feature on archiveweb.page mimics certain human behaviors like page scrolling so it's more useful for sites like Twitter, Instagram, and Facebook. For everything else, you'd have to interact with the page in order to archive it at the moment.

I'd recommend either pywb or browsertrixCrawler for something more automatic.
